export const servicesData = [
  {
    id: "1",
    icon: "/images/service/MasonryRepair.png",
    title: "Masonry Repair",
    text: "Expert brick and stone repair to restore the strength and beauty of your masonry structures.",
    link: "/calgary/masonry-repair",
  },
  {
    id: "2",
    icon: "/images/service/StoneVineer.png",
    title: "Stone Veneer",
    text: "Transform any surface with natural or manufactured stone veneer for a stunning, timeless look.",
    link: "/calgary/stone-veneer",
  },
  {
    id: "3",
    icon: "/images/service/HardscapeContractor.png",
    title: "Hardscape Contractor",
    text: "Professional hardscaping solutions including walkways, driveways, and outdoor living spaces.",
    link: "/hardscape-contractor",
  },
  {
    id: "4",
    icon: "/images/service/ChimneyRepair.png",
    title: "Chimney Repair",
    text: "Comprehensive chimney inspection, repair, and rebuilding services to keep your home safe.",
    link: "/calgary/chimney-repair",
  },
  {
    id: "5",
    icon: "/images/service/CustomFirePits.png",
    title: "Custom Fire Pits",
    text: "Design and build custom fire pits that become the centerpiece of your outdoor entertainment area.",
    link: "/calgary/custom-fire-pits",
  },
  {
    id: "6",
    icon: "/images/service/OutdorKitchen.png",
    title: "Outdoor Kitchen Contractor",
    text: "Complete outdoor kitchen construction from design to finish, built for lasting enjoyment.",
    link: "/outdoor-kitchen-contractor",
  },
  {
    id: "7",
    icon: "/images/service/PatioStone.png",
    title: "Patio Stone Installation",
    text: "Beautiful patio stone installations that enhance your outdoor space with elegance and durability.",
    link: "/patio-stone-installation",
  },
  {
    id: "8",
    icon: "/images/service/CustomPizza.png",
    title: "Custom Pizza Oven",
    text: "Handcrafted brick and stone pizza ovens built for authentic wood-fired cooking experiences.",
    link: "/calgary/custom-pizza-oven",
  },
  {
    id: "9",
    icon: "/images/service/RetainingWauit.png",
    title: "Retaining Wall Construction",
    text: "Durable retaining walls engineered for structural integrity and aesthetic appeal.",
    link: "/calgary/retaining-wall-construction",
  },
  {
    id: "10",
    icon: "/images/service/FirePlaceInsta.png",
    title: "Fireplace Installation",
    text: "Custom indoor and outdoor fireplace installations that add warmth and character to your space.",
    link: "/calgary/fireplace-installation",
  },
  {
    id: "11",
    icon: "/images/service/MasonryRepair.png",
    title: "Foundation Repair",
    text: "Expert foundation repair services to ensure the structural integrity and safety of your property.",
    link: "/calgary/foundation-repair",
  },
];
